In [1]:
import pandas as pd

data_covid = pd.read_csv("D:/KLTN/dataset_covid.csv", delimiter=",", encoding="latin-1")
data_covid

C:\Users\TUF GAMING\AppData\Local\Temp\ipykernel_7596\2011513233.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  data_covid = pd.read_csv("D:/KLTN/dataset_covid.csv", delimiter=",", encoding="latin-1")

,Patient,ravien_icdbenhchinh,ravien_icdbenhkem,sex,age,mach,nhietdo,nhiptho,chieucao,cannang,...,caccoquan_tuanhoan_binhthuong,caccoquan_tuanhoan_longnguccandoi,caccoquan_tuanhoan_timdeu,caccoquan_tuanhoan_timnhanh,caccoquan_tuanhoan_T1T2ro,caccoquan_tuanhoan_amthoibenhli,caccoquan_tuanhoan_momtimduongtrungdon,caccoquan_tuanhoan_rungmiu,caccoquan_tuanhoan_Hardzer,tienluong
0,EMR112100001663HS112100004782MNV112100000672BN...,U07.1,NaN,0,58,90,37,20,165.0,65.0,...,1,0,0,0,0,0,0,0,0,1
1,EMR112100001663HS112100004782MNV112100000672BN...,U07.1,NaN,0,60,90,37,20,165.0,65.0,...,1,0,0,0,0,0,0,0,0,1
2,EMR012200002176HS012200011018MNV012200002162BN...,U07.1,J96.0,0,59,110,37,25,160.0,63.0,...,1,0,0,0,0,0,0,0,0,1
3,EMR012200002176HS012200011018MNV012200002162BN...,U07.1,J96.0,0,59,110,37,25,160.0,63.0,...,1,0,0,0,0,0,0,0,0,1
4,EMR012200002796HS012200013001MNV012200002813BN...,U07.1,I10,0,64,85,37,28,154.0,65.0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,EMR032200002974HS032200010663MNV032200003015BN...,U07.1,A04,UNKNOWN,UNKNOWN,90,37.0,20,165.0,55.0,...,0,0,0,0,1,0,1,0,0,7
2287,EMR012200000668HS012200004902MNV012200000675BN...,U07.1,E11,UNKNOWN,UNKNOWN,90,37.0,30,165.0,55.0,...,0,1,1,0,1,0,1,0,0,7
2288,EMR012200000668HS012200004902MNV012200000675BN...,U07.1,E11,UNKNOWN,UNKNOWN,90,37.0,30,165.0,55.0,...,0,1,1,0,1,0,1,0,0,7
2289,EMR012200000677HS012200004942MNV012200000688BN...,U07.1,R77.0,UNKNOWN,UNKNOWN,78,37.0,20,155.0,65.0,...,0,1,1,0,1,0,1,0,0,7
2290,EMR012200000677HS012200004942MNV012200000688BN...,U07.1,R77.0,UNKNOWN,UNKNOWN,78,37.0,20,155.0,65.0,...,0,1,1,0,1,0,1,0,0,7

TẠO DATAFRAME

- X lấy từ cột thứ 3 (0 - 2) và trừ cột cuối cùng == feature
- y lấy cột cuối cùng làm nhãn == label

In [2]:
# Sử dụng iloc để lấy toàn bộ cột và dòng
X = data_covid.iloc[:, 3:-1]  # Lấy từ cột thứ 3 đến cột trước cột cuối cùng
y = data_covid.iloc[:, -1]  # Lấy cột cuối cùng làm nhãn

df = pd.concat([X, y], axis=1)  # Tạo DataFrame từ X và y

display(df)  # Hiển thị DataFrame

,sex,age,mach,nhietdo,nhiptho,chieucao,cannang,bmi,huyetap1,huyetap2,...,caccoquan_tuanhoan_binhthuong,caccoquan_tuanhoan_longnguccandoi,caccoquan_tuanhoan_timdeu,caccoquan_tuanhoan_timnhanh,caccoquan_tuanhoan_T1T2ro,caccoquan_tuanhoan_amthoibenhli,caccoquan_tuanhoan_momtimduongtrungdon,caccoquan_tuanhoan_rungmiu,caccoquan_tuanhoan_Hardzer,tienluong
0,0,58,90,37,20,165.0,65.0,23.88,135,80,...,1,0,0,0,0,0,0,0,0,1
1,0,60,90,37,20,165.0,65.0,23.88,135,80,...,1,0,0,0,0,0,0,0,0,1
2,0,59,110,37,25,160.0,63.0,24.61,120,70,...,1,0,0,0,0,0,0,0,0,1
3,0,59,110,37,25,160.0,63.0,24.61,120,70,...,1,0,0,0,0,0,0,0,0,1
4,0,64,85,37,28,154.0,65.0,27.41,140,90,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,UNKNOWN,UNKNOWN,90,37.0,20,165.0,55.0,20.20,100,60,...,0,0,0,0,1,0,1,0,0,7
2287,UNKNOWN,UNKNOWN,90,37.0,30,165.0,55.0,20.20,100,60,...,0,1,1,0,1,0,1,0,0,7
2288,UNKNOWN,UNKNOWN,90,37.0,30,165.0,55.0,20.20,100,60,...,0,1,1,0,1,0,1,0,0,7
2289,UNKNOWN,UNKNOWN,78,37.0,20,155.0,65.0,27.06,120,70,...,0,1,1,0,1,0,1,0,0,7
2290,UNKNOWN,UNKNOWN,78,37.0,20,155.0,65.0,27.06,120,70,...,0,1,1,0,1,0,1,0,0,7

XỬ LÍ UNKNOWN

- LabelEncoder --> Cho giá trị không phù hợp (2 - 6)
- OneHotEncoder --> Xóa cột và tạo lại cột mới --> Không đúng dữ liệu
- Gán giá trị '-1' cho các ô chứa 'UNKNOWN' trong DataFrame --> Chọn

In [3]:
# from sklearn.preprocessing import LabelEncoder

# # Tạo một bản sao của DataFrame df để thực hiện xử lý
# df_processed = df.copy()

# # Lặp qua từng cột trong DataFrame
# for column in df_processed.columns:
#     # Kiểm tra nếu kiểu dữ liệu của cột là object (chuỗi)
#     if df_processed[column].dtype == 'object':
#         # Tạo một instance mới của LabelEncoder
#         label_encoder = LabelEncoder()

#         # Thực hiện fit_transform để chuyển đổi giá trị của cột thành dạng số
#         df_processed[column] = label_encoder.fit_transform(df_processed[column].astype(str))

# # Hiển thị DataFrame sau khi xử lý
# display(df_processed)


# Tạo một bản sao của DataFrame df để thực hiện xử lý
df_processed = df.copy()

# Gán giá trị '-1' cho các ô chứa 'UNKNOWN' trong DataFrame
df_processed.replace("UNKNOWN", -1, inplace=True)

# Hiển thị DataFrame sau khi xử lý
display(df_processed)

,sex,age,mach,nhietdo,nhiptho,chieucao,cannang,bmi,huyetap1,huyetap2,...,caccoquan_tuanhoan_binhthuong,caccoquan_tuanhoan_longnguccandoi,caccoquan_tuanhoan_timdeu,caccoquan_tuanhoan_timnhanh,caccoquan_tuanhoan_T1T2ro,caccoquan_tuanhoan_amthoibenhli,caccoquan_tuanhoan_momtimduongtrungdon,caccoquan_tuanhoan_rungmiu,caccoquan_tuanhoan_Hardzer,tienluong
0,0,58,90,37,20,165.0,65.0,23.88,135,80,...,1,0,0,0,0,0,0,0,0,1
1,0,60,90,37,20,165.0,65.0,23.88,135,80,...,1,0,0,0,0,0,0,0,0,1
2,0,59,110,37,25,160.0,63.0,24.61,120,70,...,1,0,0,0,0,0,0,0,0,1
3,0,59,110,37,25,160.0,63.0,24.61,120,70,...,1,0,0,0,0,0,0,0,0,1
4,0,64,85,37,28,154.0,65.0,27.41,140,90,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2286,-1,-1,90,37.0,20,165.0,55.0,20.20,100,60,...,0,0,0,0,1,0,1,0,0,7
2287,-1,-1,90,37.0,30,165.0,55.0,20.20,100,60,...,0,1,1,0,1,0,1,0,0,7
2288,-1,-1,90,37.0,30,165.0,55.0,20.20,100,60,...,0,1,1,0,1,0,1,0,0,7
2289,-1,-1,78,37.0,20,155.0,65.0,27.06,120,70,...,0,1,1,0,1,0,1,0,0,7
2290,-1,-1,78,37.0,20,155.0,65.0,27.06,120,70,...,0,1,1,0,1,0,1,0,0,7

In [4]:
X_df_processed = df_processed.iloc[:, :-1]
y_df_processed = df_processed.iloc[:, -1]

X_df_processed.info()
y_df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2291 entries, 0 to 2290
Columns: 278 entries, sex to caccoquan_tuanhoan_Hardzer
dtypes: float64(3), int64(268), object(7)
memory usage: 4.9+ MB
<class 'pandas.core.series.Series'>
RangeIndex: 2291 entries, 0 to 2290
Series name: tienluong
Non-Null Count  Dtype
--------------  -----
2291 non-null   int64
dtypes: int64(1)
memory usage: 18.0 KB

MÔ HÌNH KNN dạng phân lớp

SVM

In [5]:
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import numpy as np
import pandas as pd

C_values = [10.0, 100.0]
kernel_values = ['linear', 'rbf', 'sigmoid']
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

X = X_df_processed.to_numpy()
y = y_df_processed.to_numpy().ravel()

evaluation_values = {
    'C': [],
    'Kernel': [],
    'Mean Accuracy': [],
    'Mean Precision': [],
    'Mean Recall': [],
    'Mean F1 Score': []
}

for C in C_values:
    for kernel in kernel_values:
        accuracy_scores = []
        precision_scores = []
        recall_scores = []
        f1_scores = []

        for train_index, test_index in skf.split(X, y):
            X_train, X_test = X[train_index], X[test_index]
            y_train, y_test = y[train_index], y[test_index]

            svm = SVC(C=C, kernel=kernel, probability=True)
            svm.fit(X_train, y_train)
            y_pred_proba = svm.predict_proba(X_test)

            y_pred = np.argmax(y_pred_proba, axis=1)

            accuracy = accuracy_score(y_test, y_pred)
            precision = precision_score(y_test, y_pred, average='micro')
            recall = recall_score(y_test, y_pred, average='micro')
            f1 = f1_score(y_test, y_pred, average='micro')

            accuracy_scores.append(accuracy)
            precision_scores.append(precision)
            recall_scores.append(recall)
            f1_scores.append(f1)

        mean_accuracy = np.mean(accuracy_scores)
        mean_precision = np.mean(precision_scores)
        mean_recall = np.mean(recall_scores)
        mean_f1_score = np.mean(f1_scores)

        print("C:", C)
        print("Kernel:", kernel)
        print("Mean Accuracy:", mean_accuracy)
        print("Trung bình Accuracy:", mean_accuracy)
        print("Trung bình Precision:", mean_precision)
        print("Trung bình Recall:", mean_recall)
        print("Trung bình F1 Score:", mean_f1_score)
        print("------------------------------")
        
        evaluation_values['C'].append(C)
        evaluation_values['Kernel'].append(kernel)
        evaluation_values['Mean Accuracy'].append(mean_accuracy)
        evaluation_values['Mean Precision'].append(mean_precision)
        evaluation_values['Mean Recall'].append(mean_recall)
        evaluation_values['Mean F1 Score'].append(mean_f1_score)

# Tạo DataFrame từ các giá trị đánh giá
df = pd.DataFrame(evaluation_values)

# Lưu DataFrame thành file CSV
df.to_csv('D:\KLTN\Danh_gia_mo_hinh\ket_qua_danh_gia_SVM_2.csv', index=False)

d:\Python\Python311\Lib\site-packages\sklearn\model_selection\_split.py:737: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

MÔ HÌNH CÂY QUYẾT ĐỊNH

MÔ HÌNH RỪNG NGẪU NHIÊN

NAIVE BAYERS